spring :
 # main :
  #  web-application-type : reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
       - id: api
         uri: lb://api
         predicates:
          - Path=/response/**
          
       - id: Vue
         uri: lb://Vue
         predicates:
          - Path=/**
         filters:
          - RewritePath=/Vue(?<segment>.*), /$\{segment}
     #  - id: BDD
      #   uri: lb://BDD
       #  predicates:
       #   - Path=/BDD/**
       #  filters:
       #   - RewritePath=/BDD/(?<segment>.*), /sujet/$\{segment}

        # filters:
        #  - RewritePath=/LoveAPI/(?<segment>.*), /sujet/$\{segment}
eureka :
  client : 
    service-url : 
      defaultZone: http://localhost:8100/eureka
server:
  port: 8200